export const LOGIN_START = 'LOGIN_START';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';


export const SEND_REQUEST_START = 'SEND_REQUEST_START';
export const SEND_REQUEST_SUCCESS = 'SEND_REQUEST_SUCCESS';
export const SEND_REQUEST_ERROR = 'SEND_REQUEST_ERROR';
export const CLEAR_ACTIONS = 'CLEAR_ACTIONS';
export const SET_FORMAT = 'SET_FORMAT';


